import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

# Path where all exports will be saved
EXPORT_DIR = os.path.join(os.path.dirname(__file__), "exports")
os.makedirs(EXPORT_DIR, exist_ok=True)

def _draw_header_footer(c, title):
    """Draws header and footer on every PDF page."""
    width, height = A4
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1 * inch, height - 0.75 * inch, f"Iris-IDEAS-TIH | {title}")

    c.setFont("Helvetica", 8)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    c.drawRightString(width - 1 * inch, 0.5 * inch, f"Generated on {timestamp}")
    c.drawString(1 * inch, 0.5 * inch, "Generated by Iris-IDEAS-TIH")

def create_pdf_from_fig(fig, title="Figure Export", filename=None):
    """
    Saves a matplotlib figure as PDF with header/footer.
    fig: matplotlib figure object
    """
    if filename is None:
        safe_title = title.replace(" ", "_")
        filename = f"{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    filepath = os.path.join(EXPORT_DIR, filename)

    # Save figure as temporary image
    temp_img = os.path.join(EXPORT_DIR, "temp_export.png")
    fig.savefig(temp_img, bbox_inches="tight")

    c = canvas.Canvas(filepath, pagesize=A4)
    _draw_header_footer(c, title)

    # Insert the saved figure image
    width, height = A4
    img = ImageReader(temp_img)
    img_width, img_height = img.getSize()
    aspect = img_height / float(img_width)
    new_width = width - 1.5 * inch
    new_height = aspect * new_width
    c.drawImage(img, 0.75 * inch, height / 2 - new_height / 2, width=new_width, height=new_height)

    c.showPage()
    c.save()

    os.remove(temp_img)
    return filepath


def create_pdf_from_dataframe(df, title="Data Export", filename=None, max_rows=15):
    """
    Saves first few rows of a dataframe to a simple text-based PDF.
    """
    if filename is None:
        safe_title = title.replace(" ", "_")
        filename = f"{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    filepath = os.path.join(EXPORT_DIR, filename)

    c = canvas.Canvas(filepath, pagesize=A4)
    _draw_header_footer(c, title)

    width, height = A4
    text = c.beginText(1 * inch, height - 1.5 * inch)
    text.setFont("Courier", 9)

    # Prepare the data text
    data_preview = df.head(max_rows).to_string(index=False)
    for line in data_preview.split("\n"):
        text.textLine(line)

    c.drawText(text)
    c.showPage()
    c.save()

    return filepath


def create_multi_fig_pdf(fig_list, title="Multi-Plot Export", filename=None):
    """
    Combines multiple matplotlib figures into one PDF file,
    each on its own page, with headers/footers.
    """
    if filename is None:
        safe_title = title.replace(" ", "_")
        filename = f"{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    filepath = os.path.join(EXPORT_DIR, filename)

    # Create a temporary folder for images
    temp_dir = os.path.join(EXPORT_DIR, "temp_images")
    os.makedirs(temp_dir, exist_ok=True)

    # Save each figure as PNG
    temp_imgs = []
    for i, fig in enumerate(fig_list, start=1):
        img_path = os.path.join(temp_dir, f"fig_{i}.png")
        fig.savefig(img_path, bbox_inches="tight")
        temp_imgs.append(img_path)

    # Create a single PDF with all images
    c = canvas.Canvas(filepath, pagesize=A4)
    width, height = A4

    for i, img_path in enumerate(temp_imgs, start=1):
        _draw_header_footer(c, f"{title} - Page {i}")
        img = ImageReader(img_path)
        img_width, img_height = img.getSize()
        aspect = img_height / float(img_width)
        new_width = width - 1.5 * inch
        new_height = aspect * new_width

        # Center the image
        c.drawImage(
            img_path,
            0.75 * inch,
            (height - new_height) / 2,
            width=new_width,
            height=new_height,
        )
        c.showPage()

    c.save()

    # Cleanup
    for img in temp_imgs:
        os.remove(img)
    os.rmdir(temp_dir)

    return filepath
